// Copyright (C) 2026 Jacob Repp
// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';
import {resolveCohort,matchesState,resourceTarget} from '../scripts/review/resolve.mjs';
import {encodePNG} from '../producers/raster/png.mjs';
import {spriteSpans,validateFamily,exportFiles,runFamily} from '../producers/blockbench/item-family.mjs';
import {itemFamily,planFamilies} from '../scripts/item-families.mjs';
function fixture(t){const root=mkdtempSync(join(tmpdir(),'review-cohort-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const write=(p,v)=>{const path=join(root,p);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,Buffer.isBuffer(v)?v:JSON.stringify(v));};write('assets/minecraft/textures/block/stone.png',encodePNG(16,16,new Uint8Array(1024).fill(255)));write('assets/minecraft/models/block/base.json',{textures:{side:'#all'},elements:[{from:[0,0,0],to:[16,16,16],faces:{south:{texture:'#side'}}}]});write('assets/minecraft/models/block/stone.json',{parent:'minecraft:block/base',textures:{all:'minecraft:block/stone'}});write('assets/minecraft/blockstates/stone.json',{variants:{'':{model:'minecraft:block/stone'}}});return{root,write,manifest:{schema:1,id:'test',entries:[{id:'minecraft:stone',kind:'block'}]}};}
test('cohorts preserve inherited textures, exact dependencies, and snapshot identity',t=>{const f=fixture(t);const a=resolveCohort(f.manifest,[f.root]);assert.deepEqual(a.entries[0].issues,[]);assert.equal(a.entries[0].dependencies.length,4);assert.equal(a.entries[0].views[0].models[0].elements[0].faces.south.texture,'assets/minecraft/textures/block/stone.png');assert.equal(resolveCohort(f.manifest,[f.root]).snapshot,a.snapshot);f.write('assets/minecraft/models/block/stone.json',{parent:'minecraft:block/base',textures:{all:'minecraft:block/stone'},credit:'edit'});assert.notEqual(resolveCohort(f.manifest,[f.root]).snapshot,a.snapshot);});
test('missing dependencies remain visible and do not acquire replacement art',t=>{const f=fixture(t);f.write('assets/minecraft/models/block/stone.json',{parent:'minecraft:block/missing'});const r=resolveCohort(f.manifest,[f.root]).entries[0];assert.equal(r.views.length,0);assert.match(r.issues[0],/Missing/);});
test('model parent cycles and alias cycles are rejected',t=>{const f=fixture(t);f.write('assets/minecraft/models/block/base.json',{parent:'minecraft:block/stone'});assert.match(resolveCohort(f.manifest,[f.root]).entries[0].issues[0],/cycle/);f.write('assets/minecraft/models/block/base.json',{textures:{all:'#side',side:'#all'},elements:[{from:[0,0,0],to:[1,1,1],faces:{south:{texture:'#all'}}}]});f.write('assets/minecraft/models/block/stone.json',{parent:'minecraft:block/base'});assert.match(resolveCohort(f.manifest,[f.root]).entries[0].issues[0],/alias cycle/);});
test('multipart conditions select parts from explicit review states',t=>{const f=fixture(t);f.write('assets/minecraft/blockstates/stone.json',{multipart:[{when:{OR:[{open:'true'},{facing:'north'}]},apply:{model:'minecraft:block/stone'}}]});assert.match(resolveCohort(f.manifest,[f.root]).entries[0].issues[0],/explicit state/);f.manifest.entries[0].states=[{label:'Open',properties:{open:'true',facing:'south'}}];assert.equal(resolveCohort(f.manifest,[f.root]).entries[0].views.length,1);assert.equal(matchesState({AND:[{half:'upper'},{facing:'north|south'}]},{half:'upper',facing:'south'}),true);});
test('cohort size, duplicate ids, and resource traversal are rejected',t=>{const f=fixture(t);assert.throws(()=>resolveCohort({...f.manifest,entries:[]},[f.root]),/1–12/);assert.throws(()=>resolveCohort({...f.manifest,entries:[...f.manifest.entries,...f.manifest.entries]},[f.root]),/Duplicate/);assert.throws(()=>resourceTarget('minecraft:../../secret','models'),/Invalid/);});
test('sprite extrusion preserves every opaque pixel and empty silhouette space',()=>{const data=new Uint8Array(1024);for(const [x,y] of [[1,2],[2,2],[4,2],[2,3]])data[(y*16+x)*4+3]=255;const spans=spriteSpans({width:16,height:16,data});const covered=new Set();for(const s of spans)for(let x=s.from[0];x<s.to[0];x++)covered.add(`${x},${15-s.from[1]}`);assert.deepEqual([...covered].sort(),['1,2','2,2','2,3','4,2']);assert.ok(spans.every(s=>s.to[2]-s.from[2]===1));data[3]=127;assert.throws(()=>spriteSpans({width:16,height:16,data}),/Partial alpha/);});
test('export preserves authored geometry and display, with no seed regeneration',()=>{const family={members:[{group:'iron_ingot',target:'assets/minecraft/models/item/iron_ingot.json',texture:'assets/minecraft/textures/item/iron_ingot.png'}]};const authored={display:{gui:{rotation:[0,15,0]}},elements:[{from:[3,4,6],to:[12,11,10],faces:{south:{texture:'#0'}}}],textures:{0:'minecraft:item/iron_ingot'}};const files=exportFiles(family,{models:[{group:'iron_ingot',content:JSON.stringify(authored)}],textures:[{name:'iron_ingot',status:'ok',content:encodePNG(16,16,new Uint8Array(1024)).toString('base64')}]});const actual=JSON.parse(files.get(family.members[0].target));assert.deepEqual(actual.elements[0].from,[3,4,6]);assert.deepEqual(actual.display,authored.display);assert.throws(()=>exportFiles(family,{models:[],textures:[]}),/Incomplete/);});
test('item families separate stateful items and keep bounded exhaustive review batches',()=>{assert.equal(itemFamily('assets/minecraft/models/item/iron_pickaxe.json'),'tools/pickaxe');assert.equal(itemFamily('assets/minecraft/models/item/crossbow.json'),'stateful/crossbow');const queue={fingerprint:'test',entries:Array.from({length:13},(_,i)=>({target:`assets/minecraft/models/item/custom${i}.json`,disposition:'select'}))};const result=planFamilies(queue);assert.deepEqual(result.families[0].batches.map(b=>b.length),[6,6,1]);assert.equal(result.families[0].family,'unclassified');});

test('initial authoring refuses to overwrite an existing retained source before contacting the editor',async()=>{
    await assert.rejects(runFamily('author','producers/blockbench/items/ingots/family.json',{port:1}),/Retained source already exists/);
});
test('family definitions reject ambiguous export ownership',()=>{
    const member={id:'minecraft:iron_ingot',group:'iron_ingot',target:'assets/minecraft/models/item/iron_ingot.json',texture:'assets/minecraft/textures/item/iron_ingot.png',seed:'producers/raster/exemplars/iron_ingot.png'};
    assert.throws(()=>validateFamily({schema:1,id:'ingots',codec:'java_block',source:'source.bbmodel',members:[member,member]}),/Duplicate/);
    assert.throws(()=>validateFamily({schema:1,id:'ingots',codec:'java_block',source:'source.bbmodel',members:[{...member,target:'assets/minecraft/models/item/gold_ingot.json'}]}),/identity/);
});
